name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          # Let the action read pnpm version from package.json "packageManager"
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm -C packages/domain build
      - run: pnpm -C apps/web exec prisma generate
      - run: pnpm -C apps/web lint
      - run: pnpm -C apps/web build
        env:
          DATABASE_URL: postgresql://placeholder
          NEXT_PUBLIC_SUPABASE_URL: https://placeholder.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: placeholder
          SUPABASE_SERVICE_ROLE_KEY: placeholder
          OPENAI_API_KEY: placeholder

